# framework.yaml
# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: "%env(APP_SECRET)%"
    csrf_protection: true
    session: true
    mailer:
        dsn: "%env(MAILER_DSN)%"

when@test:
    framework:
        test: true
        csrf_protection: true
        session:
            storage_factory_id: session.storage.factory.mock_file
