# config/packages/security.yaml
security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: "auto"

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        admin:
            pattern: ^/admin
            context: user_shared
            lazy: true
            provider: app_user_provider
            form_login:
                login_path: admin_login
                check_path: admin_login
                enable_csrf: true
                csrf_token_id: authenticate
                username_parameter: email
                password_parameter: password
                default_target_path: admin_dashboard
                always_use_default_target_path: true
            logout:
                path: app_logout
                target: home
                enable_csrf: true
                csrf_parameter: _csrf_token
                csrf_token_id: logout
                csrf_token_manager: security.csrf.token_manager
                invalidate_session: true
                delete_cookies: ["REMEMBERME_SHARED"] # <-- supprime le cookie
            remember_me:
                secret: "%kernel.secret%"
                name: REMEMBERME_SHARED
                lifetime: 604800
                path: /
                always_remember_me: true
            user_checker: App\Security\UserChecker

        main:
            context: user_shared
            lazy: true
            provider: app_user_provider
            form_login:
                login_path: app_login
                check_path: app_login
                enable_csrf: true
                csrf_token_id: authenticate
                username_parameter: email
                password_parameter: password
                default_target_path: home
                always_use_default_target_path: true
            logout:
                path: app_logout
                target: home
                enable_csrf: true
                csrf_parameter: _csrf_token
                csrf_token_id: logout
                csrf_token_manager: security.csrf.token_manager
                invalidate_session: true
                delete_cookies: ["REMEMBERME_SHARED"] # <-- supprime le cookie
            remember_me:
                secret: "%kernel.secret%"
                name: REMEMBERME_SHARED
                lifetime: 604800
                path: /
                always_remember_me: true
            user_checker: App\Security\UserChecker

    access_control:
        - { path: ^/compte/register$, roles: PUBLIC_ACCESS }
        - { path: ^/compte/verify/email$, roles: PUBLIC_ACCESS }

        # Admin
        - { path: ^/admin/login$, roles: PUBLIC_ACCESS }
        - { path: ^/admin/register$, roles: PUBLIC_ACCESS }
        - { path: ^/admin, roles: ROLE_ADMIN }

        # Webhooks / publiques
        - { path: ^/stripe/webhook$, roles: PUBLIC_ACCESS }
        - { path: ^/login$, roles: PUBLIC_ACCESS }
        - { path: ^/logout$, roles: PUBLIC_ACCESS }
        - { path: ^/register$, roles: PUBLIC_ACCESS }
        - { path: ^/products, roles: PUBLIC_ACCESS }
        - { path: ^/home, roles: PUBLIC_ACCESS }
        - { path: ^/$, roles: PUBLIC_ACCESS }

        # Zones protégées
        - { path: ^/cart, roles: ROLE_USER }
        - { path: ^/order, roles: ROLE_USER }
        - { path: ^/profile, roles: ROLE_USER }
        - { path: ^/compte, roles: ROLE_USER } # en dernier: catch-all /compte

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10
